### ISSUE TITLE
Docker issue web module

### ISSUE THREAD

**Issue by ggardiakos** [fengxia41103/stock#1]
hi! can you please help me? :)

![2021-09-30 00_26_34-New Issue · fengxia41103_stock — Mozilla Firefox](https://user-images.githubusercontent.com/69169466/135392556-77852aea-2490-4499-93e9-63b5cf4890b8.png)

**Comment by fengxia41103** [comment]
Hi,
 
Did you run `docker-compose up --build`? Looks to me you don't have the docker image built yet. 

You can confirm the image by `docker container ls`, and look for two images named `backend_stock` and `frontend_stock`. If you don't see them, there is something missing about the images.

If you are familiar w/ docker CLI, you can also build the image separately. You will find the `Dockerfile` under the `/backend` folder and the `/frontend` folder.

Hope this helps.

**Comment by ggardiakos** [comment]
getting there haha 
![image](https://user-images.githubusercontent.com/69169466/135741896-22bf4a09-f42d-47f4-acbf-70949572607d.png)
 is the image missing?

**Comment by ggardiakos** [comment]
ok, I was able to get the front end going I think I changed node to node:latest can you help with this? :) 
![image](https://user-images.githubusercontent.com/69169466/135743101-0d1a66fa-99bb-4465-ac86-145a5aadb3c6.png)

**Comment by ggardiakos** [comment]
ok kinda getting somewhere but still can't get passed this 
![image](https://user-images.githubusercontent.com/69169466/135743234-a0f9587b-d30c-4845-b40c-a5fc607a6be4.png)

**Comment by ggardiakos** [comment]
I added the static folder to the backend folder and I think that did it! :)

**Comment by ggardiakos** [comment]
I also turned of dockerf v2 release candidate

![image](https://user-images.githubusercontent.com/69169466/135953201-e04c1547-ab96-4d1f-8389-8a29be00f9d9.png)

**Comment by ggardiakos** [comment]
thank you! you're amazing!
