### ISSUE TITLE
Add New Stocks Dialog

### ISSUE THREAD

**Issue by rwespey** [fengxia41103/stock#4]
I clicked on ADD NEW STOCKS to begin adding new stocks....A couple of issues here:
1. As discussed, the user should create a Sector, but the dialog does not give me the ability to either add a sector or a link to the sector page. 
2. After adding the stock, I get the message that the stock was added to my portfolio, but I'm taken back to the Dashboard page.  At this point, it would make more sense to take me to either the Stock page or the Sector page.
3. When I go to the sector page, the stock was automatically added to the demo sector.  It would be better to allow me to assign/create a sector when I add the stock initially.

**Comment by fengxia41103** [comment]
Since we have a demo sector created for a new user. I'm closing this one.
