### ISSUE TITLE
Stock Page

### ISSUE THREAD

**Issue by rwespey** [fengxia41103/stock#5]
When I go to the Stock page, I see the Last Reporting Date for the stock.  However, I do not see any way to add notes for the specific stock. It would be nice to allow me to add a stock-specific note for a stock either from the Stocks page or from the page that shows the stock details.  When I click on a specific stock, the My Notes pane appears briefly, but then it goes away.

**Comment by rwespey** [comment]
I just found the My Notes section for a specific stock.  When I initially go to the specific stock page, the My Notes section appears briefly at the  top and then "disappears."  It turns out that the My Notes section actually moves to the bottom of the page. 

A better user experience IMHO would be to enable a Notes icon so that I can easily see it.  When clicking the icon, it would be nice to be able to choose either a general note or a stock-specific note.

**Comment by fengxia41103** [comment]
See #6, #7.

There was a bug in note creation API. So that could also be the cause of this 404 since creation failed **silently**, thus the next poll will return nothing.

**Comment by fengxia41103** [comment]
> > One final issue. I added a new Note from the specific stock page and I clicked Save. However, the note does NOT appear to actually be showing up? I refreshed the page, but the note does not show on the page.
> > Next I went to the My Notes page and attempted to create a general note. After saving, I attempted to refresh the page and got a 404 error?
> 
> Hmm... likely a user permission issue. Let me look into this.

Regarding this, see comment in #7. If the content doesn't include stock's symbol, the API filter will not return this note as _related to_ this stock. The new change is now appending the symbol if content doesn't have it already. Thus it's ensured that stock's symbol will always be there. This should prevent this possibility from happening now.
