### ISSUE TITLE
My Notes - 404 Error

### ISSUE THREAD

**Issue by rwespey** [fengxia41103/stock#7]
When I attempt to add a Note to the My Notes page, the result is that the My Notes page comes up with a 404 error (the My Notes page appears just fine until I add a Note).  The error in the command line is as follows:

`web_1            | [25/Oct/2021 19:23:36] "GET /api/v1/stocks/ HTTP/1.1" 200 483
backend-proxy_1  | 172.21.0.1 - - [25/Oct/2021:19:23:36 +0000] "GET /api/v1/stocks/ HTTP/1.1" 200 483 "http://localhost:8084/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36" "-"

web_1            | Internal Server Error: /api/v1/diaries/

web_1            | Traceback (most recent call last):

web_1            |   File "/usr/local/lib/python3.8/site-packages/tastypie/resources.py", line 227, in wrapper

web_1            |     response = callback(request, *args, **kwargs)

web_1            |   File "/usr/local/lib/python3.8/site-packages/tastypie/resources.py", line 467, in dispatch_list

web_1            |     return self.dispatch('list', request, **kwargs)

web_1            |   File "/usr/local/lib/python3.8/site-packages/tastypie/resources.py", line 499, in dispatch

web_1            |     response = method(request, **kwargs)

web_1            |   File "/usr/local/lib/python3.8/site-packages/tastypie/resources.py", line 1362, in get_list

web_1            |     bundles = [

web_1            |   File "/usr/local/lib/python3.8/site-packages/tastypie/resources.py", line 1363, in <listcomp>

web_1            |     self.full_dehydrate(self.build_bundle(obj=obj, request=request), for_list=True)

web_1            |   File "/usr/local/lib/python3.8/site-packages/tastypie/resources.py", line 912, in full_dehydrate

web_1            |     data[field_name] = field_object.dehydrate(bundle, for_list=for_list)

web_1            |   File "/usr/local/lib/python3.8/site-packages/tastypie/fields.py", line 130, in dehydrate

web_1            |     current_object = getattr(current_object, attr, None)

web_1            |   File "/code/stock/models.py", line 1668, in is_correct

web_1            |     if stock.latest_close_price >= self.price and self.judgement == 1:

web_1            | TypeError: '>=' not supported between instances of 'NoneType' and 'int'

web_1            | Internal Server Error: /api/v1/diaries/

web_1            | [25/Oct/2021 19:23:36] "GET /api/v1/diaries/ HTTP/1.1" 500 1424
backend-proxy_1  | 172.21.0.1 - - [25/Oct/2021:19:23:36 +0000] "GET /api/v1/diaries/ HTTP/1.1" 500 1424 "http://localhost:8084/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36" "-"`

**Comment by fengxia41103** [comment]
By looking at this line, the stock doesn't yet have a price. This can be seen in a couple scenarios:

1. A new symbol added, but price pulling has not yet executed.
2. New symbol added, but price pulling failed. Currently, task status is silent. We are to add a feature to show ongoing task and its failure, if any. That will help this case.
3. Wrong symbol. Could be a typo, thus price pulling failed.

In any case, we should guard against `latest_close_price` being None.

```
if stock.latest_close_price >= self.price and self.judgement == 1:
```

**Comment by fengxia41103** [comment]
See 7d98e57.

`stock.last_close_price` can be None, but `self.price` is either a valid price or 0. This was the cause of this bug.
